'use strict';

const actionTypes = {
  SHOW_OVERLAY: 'SHOW_OVERLAY',
  HIDE_OVERLAY: 'HIDE_OVERLAY',
  DELETE_PROJECT_CONFIRM: 'DELETE_PROJECT_CONFIRM',
  RX_ON: 'RX_ON',
  RX_OFF: 'RX_OFF',
  TX_ON: 'TX_ON',
  TX_OFF: 'TX_OFF',
  TRANSMIT: 'TRANSMIT',
  UPDATE_DURATION: 'UPDATE_DURATION',
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT'
};

module.exports = actionTypes;
