'use strict';

const actionTypes = {
  SHOW_OVERLAY: 'SHOW_OVERLAY',
  HIDE_OVERLAY: 'HIDE_OVERLAY',
  DELETE_PROJECT_CONFIRM: 'DELETE_PROJECT_CONFIRM',
  ECHO_ON: 'ECHO_ON',
  ECHO_OFF: 'ECHO_OFF',
  RX_ON: 'RX_ON',
  RX_OFF: 'RX_OFF',
  RX_CLEAR_TIMEOUT: 'RX_CLEAR_TIMEOUT',
  TX_ON: 'TX_ON',
  TX_OFF: 'TX_OFF',
  TX_CLEAR_TIMEOUT: 'TX_CLEAR_TIMEOUT',
  RECEIVE: 'RECEIVE',
  TRANSMIT: 'TRANSMIT',
  UPDATE_DURATION: 'UPDATE_DURATION',
  CLEAR_TRANSMISSION: 'CLEAR_TRANSMISSION',
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  RELOAD_DEVICES: 'RELOAD_DEVICES',
  UPDATE_DEVICES: 'UPDATE_DEVICES',
  ENABLE_AUTO_DOWNLOAD: 'ENABLE_AUTO_DOWNLOAD',
  DISABLE_AUTO_DOWNLOAD: 'DISABLE_AUTO_DOWNLOAD',
  UPDATE_SEARCH_STATUS: 'UPDATE_SEARCH_STATUS',
  CLEAR_SEARCH_STATUS: 'CLEAR_SEARCH_STATUS',
  UPDATE_SELECTED_DEVICE: 'UPDATE_SELECTED_DEVICE',
  RESET_DOWNLOAD_PROGRESS: 'RESET_DOWNLOAD_PROGRESS',
  UPDATE_DOWNLOAD_PROGRESS: 'UPDATE_DOWNLOAD_PROGRESS',
  QUEUE_NEW_FILE: 'QUEUE_NEW_FILE',
  QUEUE_CHANGE_FILE: 'QUEUE_CHANGE_FILE',
  QUEUE_OVERWRITE_FILE: 'QUEUE_OVERWRITE_FILE',
  RESET_ACTION_QUEUE: 'RESET_ACTION_QUEUE'
};

module.exports = actionTypes;
