'use strict';

const actionTypes = {
  SHOW_OVERLAY: 'SHOW_OVERLAY',
  HIDE_OVERLAY: 'HIDE_OVERLAY',
  DELETE_PROJECT_CONFIRM: 'DELETE_PROJECT_CONFIRM',
  RX_ON: 'RX_ON',
  RX_OFF: 'RX_OFF',
  TX_ON: 'TX_ON',
  TX_OFF: 'TX_OFF',
  RECEIVE: 'RECEIVE',
  TRANSMIT: 'TRANSMIT',
  UPDATE_DURATION: 'UPDATE_DURATION',
  CLEAR_TRANSMISSION: 'CLEAR_TRANSMISSION',
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  RELOAD_DEVICES: 'RELOAD_DEVICES',
  UPDATE_DEVICES: 'UPDATE_DEVICES',
  ENABLE_AUTO_DOWNLOAD: 'ENABLE_AUTO_DOWNLOAD',
  DISABLE_AUTO_DOWNLOAD: 'DISABLE_AUTO_DOWNLOAD',
  UPDATE_SEARCH_STATUS: 'UPDATE_SEARCH_STATUS',
  CLEAR_SEARCH_STATUS: 'CLEAR_SEARCH_STATUS',
  UPDATE_SELECTED_DEVICE: 'UPDATE_SELECTED_DEVICE',
  RESET_DOWNLOAD_PROGRESS: 'RESET_DOWNLOAD_PROGRESS',
  UPDATE_DOWNLOAD_PROGRESS: 'UPDATE_DOWNLOAD_PROGRESS'
};

module.exports = actionTypes;
