'use strict';

const overlayStates = {
  SAVE_OVERLAY: 'SAVE_OVERLAY',
  DOWNLOAD_OVERLAY: 'DOWNLOAD_OVERLAY',
  PROJECTS_OVERLAY: 'PROJECTS_OVERLAY',
  DELETE_FILE_OVERLAY: 'DELETE_FILE_OVERLAY',
  DELETE_PROJECT_OVERLAY: 'DELETE_PROJECT_OVERLAY'
};

module.exports = overlayStates;
