'use strict';

const overlayStates = {
  NO_OVERLAY: 'NO_OVERLAY',
  HELP_OVERLAY: 'HELP_OVERLAY',
  SAVE_OVERLAY: 'SAVE_OVERLAY',
  DOWNLOAD_OVERLAY: 'DOWNLOAD_OVERLAY',
  PROJECTS_OVERLAY: 'PROJECTS_OVERLAY',
  OVERWRITE_OVERLAY: 'OVERWRITE_OVERLAY',
  NEW_VERSION_OVERLAY: 'NEW_VERSION_OVERLAY',
  DELETE_FILE_OVERLAY: 'DELETE_FILE_OVERLAY',
  SAVE_ON_CHANGE_OVERLAY: 'SAVE_ON_CHANGE_OVERLAY',
  DELETE_PROJECT_OVERLAY: 'DELETE_PROJECT_OVERLAY'
};

module.exports = overlayStates;
